
class Autogenerated {
  List<Accounts> accounts;

  Autogenerated({this.accounts});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['accounts'] != null) {
      accounts = new List<Accounts>();
      json['accounts'].forEach((v) {
        accounts.add(new Accounts.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.accounts != null) {
      data['accounts'] = this.accounts.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Accounts {
  String accountNumber;
  int availableCredit;
  double balance;
  String bankId;
  int certainDate;
  String credentialsId;
  bool excluded;
  bool favored;
  String id;
  String name;
  int ownership;
  Null payload;
  String type;
  String userId;
  bool userModifiedExcluded;
  bool userModifiedName;
  bool userModifiedType;
  String identifiers;
  Null transferDestinations;
  Null details;
  Images images;
  String holderName;
  bool closed;
  String flags;
  String accountExclusion;
  String currencyCode;
  CurrencyDenominatedBalance currencyDenominatedBalance;
  int refreshed;
  String financialInstitutionId;

  Accounts(
      {this.accountNumber,
        this.availableCredit,
        this.balance,
        this.bankId,
        this.certainDate,
        this.credentialsId,
        this.excluded,
        this.favored,
        this.id,
        this.name,
        this.ownership,
        this.payload,
        this.type,
        this.userId,
        this.userModifiedExcluded,
        this.userModifiedName,
        this.userModifiedType,
        this.identifiers,
        this.transferDestinations,
        this.details,
        this.images,
        this.holderName,
        this.closed,
        this.flags,
        this.accountExclusion,
        this.currencyCode,
        this.currencyDenominatedBalance,
        this.refreshed,
        this.financialInstitutionId});

  Accounts.fromJson(Map<String, dynamic> json) {
    accountNumber = json['accountNumber'];
    availableCredit = json['availableCredit'];
    balance = json['balance'];
    bankId = json['bankId'];
    certainDate = json['certainDate'];
    credentialsId = json['credentialsId'];
    excluded = json['excluded'];
    favored = json['favored'];
    id = json['id'];
    name = json['name'];
    ownership = json['ownership'];
    payload = json['payload'];
    type = json['type'];
    userId = json['userId'];
    userModifiedExcluded = json['userModifiedExcluded'];
    userModifiedName = json['userModifiedName'];
    userModifiedType = json['userModifiedType'];
    identifiers = json['identifiers'];
    transferDestinations = json['transferDestinations'];
    details = json['details'];
    images =
    json['images'] != null ? new Images.fromJson(json['images']) : null;
    holderName = json['holderName'];
    closed = json['closed'];
    flags = json['flags'];
    accountExclusion = json['accountExclusion'];
    currencyCode = json['currencyCode'];
    currencyDenominatedBalance = json['currencyDenominatedBalance'] != null
        ? new CurrencyDenominatedBalance.fromJson(
        json['currencyDenominatedBalance'])
        : null;
    refreshed = json['refreshed'];
    financialInstitutionId = json['financialInstitutionId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['accountNumber'] = this.accountNumber;
    data['availableCredit'] = this.availableCredit;
    data['balance'] = this.balance;
    data['bankId'] = this.bankId;
    data['certainDate'] = this.certainDate;
    data['credentialsId'] = this.credentialsId;
    data['excluded'] = this.excluded;
    data['favored'] = this.favored;
    data['id'] = this.id;
    data['name'] = this.name;
    data['ownership'] = this.ownership;
    data['payload'] = this.payload;
    data['type'] = this.type;
    data['userId'] = this.userId;
    data['userModifiedExcluded'] = this.userModifiedExcluded;
    data['userModifiedName'] = this.userModifiedName;
    data['userModifiedType'] = this.userModifiedType;
    data['identifiers'] = this.identifiers;
    data['transferDestinations'] = this.transferDestinations;
    data['details'] = this.details;
    if (this.images != null) {
      data['images'] = this.images.toJson();
    }
    data['holderName'] = this.holderName;
    data['closed'] = this.closed;
    data['flags'] = this.flags;
    data['accountExclusion'] = this.accountExclusion;
    data['currencyCode'] = this.currencyCode;
    if (this.currencyDenominatedBalance != null) {
      data['currencyDenominatedBalance'] =
          this.currencyDenominatedBalance.toJson();
    }
    data['refreshed'] = this.refreshed;
    data['financialInstitutionId'] = this.financialInstitutionId;
    return data;
  }
}

class Images {
  String icon;
  Null banner;

  Images({this.icon, this.banner});

  Images.fromJson(Map<String, dynamic> json) {
    icon = json['icon'];
    banner = json['banner'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['icon'] = this.icon;
    data['banner'] = this.banner;
    return data;
  }
}

class CurrencyDenominatedBalance {
  int unscaledValue;
  int scale;
  String currencyCode;

  CurrencyDenominatedBalance(
      {this.unscaledValue, this.scale, this.currencyCode});

  CurrencyDenominatedBalance.fromJson(Map<String, dynamic> json) {
    unscaledValue = json['unscaledValue'];
    scale = json['scale'];
    currencyCode = json['currencyCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['unscaledValue'] = this.unscaledValue;
    data['scale'] = this.scale;
    data['currencyCode'] = this.currencyCode;
    return data;
  }
}